version: 2

project_name: c_bin_pocketbase

dist: dist

before:
  hooks:
    - go mod tidy

builds:
  - id: cgo_build
    main: ./main.go
    binary: c_bin_pocketbase
    ldflags:
      - -s -w -X github.com/erolisdev/c_bin_pocketbase.Version={{ .Version }}
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: archive_cgo
    builds: [cgo_build]
    format: zip
    # files:
    #   - LICENSE.md
    #   - README.md

checksum:
  name_template: "checksums.txt"

release:
  draft: false

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
