// Autogenerated by github.com/snonky/pocketbase-gogen.
// Please feel free to edit after noting the explanation:
//
// This file is an intermediate product of the proxy generation.
// It is called a 'schema as code' or just 'template'. It is not meant to be
// compiled it is only meant for human interaction, place it in a separate package
// but never import it.
// Here's what you can do to influence the final code generation step:
//
// Do:
//   - Edit the struct names. The names are directly copied to the proxy struct definitions.
//   - Remove structs or fields that you don't want in the generated code. Note that upon removing a struct
//     you also have to remove any fields that have that struct as their type.
//   - Edit the type name in the '// select:' comments.
//   - Change the const names of the select options by adding a pair of [] to the // select: comment.
//     Example: // select: MySelectType(optionA, optionB)[OpA, OpB] <-- These constants will represent
//     the select options (like an enum). If you omit the [] the option names are used directly.
//   - Edit the field names. If you do, the generator still needs to know the original database field name.
//     To provide this, add a '// schema-name: [original field name]' comment directly above the field.
//   - Add methods to the template structs. The generator will replace any fields you access with the also
//     generated getters/setters. Be aware of that when repeatedly assigning a template field. You are
//     calling a setter on every assignment. The methods can also call each other.
//
// Do not:
//   - Add structs that do not represent a PB collection.
//   - Add fields that are not part of the PB schema to the structs.
//   - Change the '// collection-name:' comments unless the collection was actually renamed.
//     If the comment is missing from the first struct field, the generator will print a warning.
//   - Change the select values in the () of the '// select:' comments'
//   - Remove the '// system:' doc comments from the system fields. Generation will fail if you do so.
//   - Shadow any names from the core.Record struct. Generation will also fail for safety.
//   - Rename fields without preserving the original name with a '// schema-name:' comment.'
//
// If you edit this file, be careful and back it up to prevent the changes from being overridden by
// subsequent runs of the template command. Check out the PocketBase docs to find out how to use the
// generated code in your code: https://pocketbase.io/docs/go-record-proxy/
package pbschema

import "github.com/pocketbase/pocketbase/tools/types"

type Users struct {
	// collection-name: users
	// system: id
	Id string
	// system: password
	password string
	// system: tokenKey
	tokenKey string
	// system: email
	email string
	// system: emailVisibility
	emailVisibility bool
	// system: verified
	verified bool
	name     string
	avatar   string
	created  types.DateTime
	updated  types.DateTime
}

type TaxRates struct {
	// collection-name: tax_rates
	// system: id
	Id          string
	description string
	type_       string
	rate        float64
	updated     types.DateTime
	created     types.DateTime
}

type Categories struct {
	// collection-name: categories
	// system: id
	Id                string
	name              string
	category_id       float64
	column            float64
	status            float64
	sort_order        float64
	show_in_suggested float64
	image_url         string
	description       string
	updated           types.DateTime
	created           types.DateTime
}

type PaymentMethods struct {
	// collection-name: payment_methods
	// system: id
	Id      string  
	name    string
	type_   string
	status  bool
	updated types.DateTime
	created types.DateTime
}

type Options struct {
	// collection-name: options
	// system: id
	Id                string
	option_id         float64
	name              string
	type_             string
	sort_order        float64
	title             float64
	option_group      float64
	required          float64
	free_option_count float64
	max_option_count  float64
	option_desc       string
	updated           types.DateTime
	created           types.DateTime
}

type OptionValues struct {
	// collection-name: option_values
	// system: id
	Id                string
	option            *Options
	option_value_id   float64
	sort_order        float64
	related_option_id string
	price_ht          float64
	price_ttc         float64
	tax_rate          *TaxRates
	price_status      string
	reset             float64
	grup              string
	status            float64
	not_recommanded   float64
	image_type        float64
	image_url         string
	desc              string
	model             string
	updated           types.DateTime
	created           types.DateTime
}

type Products struct {
	// collection-name: products
	// system: id
	Id                string
	product_id        float64
	name              string
	price_ht          float64
	price_ttc         float64
	status            float64
	private           float64
	show_in_suggested float64
	shipping          float64
	category_id       float64
	isFullWidth       float64
	sort_order        float64
	c_sort_order      float64
	image_url         string
	related           string
	description       string
	printer_id        float64
	printer_ip        string
	printer_port      float64
	template_id       float64
	label_printer_id  string
	model             string
	tax_rate          *TaxRates
	category          *Options
	updated           types.DateTime
	created           types.DateTime
}

type Customers struct {
	// collection-name: customers
	// system: id
	Id string
	// system: password
	password string
	// system: tokenKey
	tokenKey string
	// system: email
	email string
	// system: emailVisibility
	emailVisibility bool
	// system: verified
	verified       bool
	firstname      string
	lastname       string
	telephone      string
	company        string
	address        string
	reward         string
	reward_history string
	model          string
	updated        types.DateTime
	created        types.DateTime
}

type LiveOrders struct {
	// collection-name: live_orders
	// system: id
	Id                 string
	local_order_id     float64
	order_number       float64
	remote_order_id    float64
	web_order_number   float64
	process            string
	pos_number         string
	total_tax          float64
	total_w_tax        float64
	total_discount     float64
	remainder          float64
	caissier           string
	order_status_id    string
	table_no           string
	delivery_time      string
	delivery_minute    string
	order_time         string
	order_customer     string
	date               string
	name               string
	shipping_firstname string
	is_merged          bool
	merged_orders      string
	merged_local_ids   string
	customer           *Customers
	updated            types.DateTime
	created            types.DateTime
}

type LiveOrderProducts struct {
	// collection-name: live_order_products
	// system: id
	Id              string
	live_order      *LiveOrders
	local_order_id  float64
	product_id      float64
	unit            string
	status          bool
	quantity_unit   float64
	uprice_w_tax    float64
	uprice_standart float64
	prix_revt       float64
	total_row_tax   float64
	total_row_w_tax float64
	tax_rate        *TaxRates
	created_by      string
	updated_by      string
	name            string
	image           string
	customer        *Customers
	updated         types.DateTime
	created         types.DateTime
}

type LiveOrderProductOptions struct {
	// collection-name: live_order_product_options
	// system: id
	Id                 string
	live_order         *LiveOrderProducts
	live_order_product *LiveOrderProducts
	local_order_id     float64
	status             bool
	product_id         float64
	option_id          float64
	option_value_id    float64
	unit               string
	quantity_unit      float64
	uprice_w_tax       float64
	uprice_standart    float64
	prix_revt          float64
	total_row_tax      float64
	total_row_w_tax    float64
	tax_rate           *TaxRates
	created_by         string
	updated_by         string
	name               string
	image              string
	customer           *Customers
	updated            types.DateTime
	created            types.DateTime
}

type Tickets struct {
	// collection-name: tickets
	// system: id
	Id                   string
	ticket_id            float64
	ticket_no            float64
	order_number         float64
	web_order_number     float64
	ticket_datetime      string
	caissier             string
	total_amount_ht      float64
	total_tax_amount     float64
	total_amount_ttc     float64
	previous_record_hash string
	current_record_hash  string
	model                string
	customer             *Customers
	customer_fullname    string
	updated              types.DateTime
	created              types.DateTime
}

type TicketLines struct {
	// collection-name: ticket_lines
	// system: id
	Id                   string
	ticket               *Tickets
	product              *Products
	unit                 string
	quantity_unit        float64
	base_price_ht        float64
	base_tax_rate        float64
	chosen_options       string
	calculated_total_ht  float64
	calculated_total_tax float64
	calculated_total_ttc float64
	total_tax_amount     float64
	total_amount_ttc     float64
	previous_record_hash string
	current_record_hash  string
	updated              types.DateTime
	created              types.DateTime
}

type Returns struct {
	// collection-name: returns
	// system: id
	Id              string
	original_ticket *Tickets
	ticket_no       float64
	// select: ReturnTypeSelectType(RETURN, CANCELLATION, OTHER)
	return_type               int
	return_datetime           string
	total_amount_ht_returned  float64
	total_tax_amount_returned float64
	total_amount_ttc_returned float64
	previous_record_hash      string
	current_record_hash       string
	customer                  *Customers
	updated                   types.DateTime
	created                   types.DateTime
}

type ReturnItems struct {
	// collection-name: return_items
	// system: id
	Id                     string
	return_record          *Returns
	original_ticket_line   *TicketLines
	unit                   string
	quantity_unit_returned float64
	total_ht_returned      float64
	total_tax_returned     float64
	total_ttc_returned     float64
	previous_record_hash   string
	current_record_hash    string
	updated                types.DateTime
	created                types.DateTime
}

type Payments struct {
	// collection-name: payments
	// system: id
	Id                        string
	payment_method            *PaymentMethods
	payment_datetime          string
	currency                  string
	transaction_reference     string
	amount                    float64
	cash_received             float64
	cash_change_given         float64
	total_tax_amount_returned float64
	total_amount_ttc_returned float64
	previous_record_hash      string
	current_record_hash       string
	updated                   types.DateTime
	created                   types.DateTime
}

type AuditLogs struct {
	// collection-name: audit_logs
	// system: id
	Id                   string
	timestamp            string
	user                 *Users
	action               string
	details              string
	previous_record_hash string
	current_record_hash  string
	updated              types.DateTime
	created              types.DateTime
}

type ReportingTicketLineOptions struct {
	// collection-name: reporting_ticket_line_options
	// system: id
	Id            string
	ticket        *Tickets
	ticket_line   *TicketLines
	option_value  *OptionValues
	name          string
	price_ttc     float64
	unit          string
	quantity_unit float64
	total_ttc     float64
	updated       types.DateTime
	created       types.DateTime
}

type ClosuresReports struct {
	// collection-name: closures_reports
	// system: id
	Id                   string
	timestamp            string
	user                 *Users
	action               string
	details              string
	previous_record_hash string
	current_record_hash  string
	updated              types.DateTime
	created              types.DateTime
}
