version: 2

project_name: c_bin_pocketbase

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - id: build_noncgo
    main: ./main.go  # main.go dosyanız proje kök dizininde olduğu için böyle belirtmelisiniz
    binary: c_bin_pocketbase
    ldflags:
      - -s -w -X github.com/erolisdev/c_bin_pocketbase.Version={{ .Version }}
    env:
      - CGO_ENABLED=1  # CGO etkinleştirildi
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: ppc64le
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: ppc64le

release:
  draft: true  # Yayınlamadan önce taslak olarak bırakılabilir

archives:
  - id: archive_noncgo
    builds: [build_noncgo]
    format: zip
    files:
      - LICENSE.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'
      - '^ui:'
