name: Release

on:
  push:
    tags:
      - "v*" # Sadece v1.0.0 gibi tag'ler çalıştırır

jobs:
  build:
    name: Build & Release Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.23.9"

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build Go binary with CGO_ENABLED=1
        run: |
          mkdir -p build
          export CGO_ENABLED=1
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}
          EXT=""
          if [ "$GOOS" = "windows" ]; then EXT=".exe"; fi
          go build -v -o build/c_bin_pocketbase-${GOOS}-${GOARCH}${EXT}

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
