name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.23.5"

      - name: Set up Node.js (Opsiyonel — PocketBase gibi UI varsa gerekebilir)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run tests
        run: go test ./...

      - name: Install MinGW-w64 cross compiler
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CC: x86_64-w64-mingw32-gcc
